version: '3'

services:
  db:
    image: 'mongo:3.6'
    volumes:
      - ./.mongodb:/data/db
  rest:
    image: 'kphongph/mongo-rest'
    environment:
      - MONGODB_URL=mongodb://db:27017
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:27017", "--", "node", "app.js", "--jwt_secret=test","--mongodb_url=mongodb://db:27017"] 
  react:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "3001:3000"
